using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace STLServerlessNET.Entities.Web;

[Table("users")]
[Index("UserEmail", Name = "user_email")]
//[Index("UserEmail", "UserPassword", "Active", Name = "user_email_user_password_active")]
public partial class User
{
    [Key]
    [Column("user_id", TypeName = "int(11)")]
    public int UserId { get; set; }

    [Column("user_type", TypeName = "enum('user','dealer','sales_agent')")]
    public string UserType { get; set; } = null!;

    [Column("user_email")]
    [StringLength(125)]
    public string UserEmail { get; set; } = null!;

    //[Column("user_password")]
    //[MySqlCollation("utf8mb3_bin")]
    //public string? UserPassword { get; set; }

    //[Column("user_password_last_1")]
    //[StringLength(255)]
    //[MySqlCollation("utf8mb3_bin")]
    //public string? UserPasswordLast1 { get; set; }

    //[Column("user_password_last_2")]
    //[StringLength(255)]
    //[MySqlCollation("utf8mb3_bin")]
    //public string? UserPasswordLast2 { get; set; }

    //[Column("password_last_updated", TypeName = "datetime")]
    //public DateTime PasswordLastUpdated { get; set; }

    [Column("first_name")]
    [StringLength(35)]
    public string FirstName { get; set; } = null!;

    [Column("last_name")]
    [StringLength(35)]
    public string LastName { get; set; } = null!;

    [Column("suffix")]
    [StringLength(125)]
    public string? Suffix { get; set; }

    [Column("company")]
    [StringLength(35)]
    public string? Company { get; set; }

    [Column("phone")]
    [StringLength(25)]
    public string Phone { get; set; } = null!;

    [Column("phone_extension")]
    [StringLength(25)]
    public string PhoneExtension { get; set; } = null!;

    [Column("bill_street")]
    [StringLength(125)]
    public string BillStreet { get; set; } = null!;

    [Column("bill_apt")]
    [StringLength(125)]
    public string BillApt { get; set; } = null!;

    [Column("bill_apt_suffix")]
    [StringLength(125)]
    public string? BillAptSuffix { get; set; }

    [Column("bill_city")]
    [StringLength(125)]
    public string BillCity { get; set; } = null!;

    [Column("bill_state")]
    [StringLength(10)]
    public string BillState { get; set; } = null!;

    [Column("bill_zip")]
    [StringLength(15)]
    public string BillZip { get; set; } = null!;

    [Column("bill_country")]
    [StringLength(125)]
    public string BillCountry { get; set; } = null!;

    [Column("billing_id", TypeName = "int(11)")]
    public int BillingId { get; set; }

    [Column("attention")]
    [StringLength(35)]
    public string? Attention { get; set; }

    [Column("ship_apt")]
    [StringLength(80)]
    public string ShipApt { get; set; } = null!;

    [Column("ship_apt_suffix")]
    [StringLength(80)]
    public string? ShipAptSuffix { get; set; }

    [Column("ship_street")]
    [StringLength(125)]
    public string ShipStreet { get; set; } = null!;

    [Column("ship_city")]
    [StringLength(125)]
    public string ShipCity { get; set; } = null!;

    [Column("ship_state")]
    [StringLength(10)]
    public string ShipState { get; set; } = null!;

    [Column("ship_zip")]
    [StringLength(15)]
    public string ShipZip { get; set; } = null!;

    [Column("ship_country")]
    [StringLength(15)]
    public string ShipCountry { get; set; } = null!;

    [Column("shipping_id", TypeName = "int(11)")]
    public int ShippingId { get; set; }

    [Column("active", TypeName = "enum('Y','N')")]
    public string Active { get; set; } = null!;

    [Column("tax_exempt", TypeName = "enum('Y','N')")]
    public string TaxExempt { get; set; } = null!;

    [Column("fishbowl_id")]
    [StringLength(100)]
    public string? FishbowlId { get; set; }

    //[Column("failed_attempts", TypeName = "int(11)")]
    //public int? FailedAttempts { get; set; }

    [Column("unclaimed", TypeName = "int(11)")]
    public int? Unclaimed { get; set; }

    [Column("auto_generated", TypeName = "int(11)")]
    public int? AutoGenerated { get; set; }

    //[Column("last_failed_attempt_at", TypeName = "datetime")]
    //public DateTime? LastFailedAttemptAt { get; set; }

    [Column("create_date", TypeName = "timestamp")]
    public DateTime CreateDate { get; set; }

    [Column("update_date", TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    //[Column("dealer_app_submitted", TypeName = "enum('Y','N')")]
    //public string? DealerAppSubmitted { get; set; }

    //[Column("converted_from_user", TypeName = "enum('Y','N')")]
    //public string? ConvertedFromUser { get; set; }
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}