using System.ComponentModel.DataAnnotations.Schema;

namespace STLServerlessNET.Entities.Service;

[Table("users")]
public partial class User
{
    public int UserId { get; set; }

    public string UserType { get; set; } = null!;

    public string UserEmail { get; set; } = null!;

    public string? UserPassword { get; set; }

    public string? UserPasswordLast1 { get; set; }

    public string? UserPasswordLast2 { get; set; }

    public DateTime PasswordLastUpdated { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string? Suffix { get; set; }

    public string? Company { get; set; }

    public string Phone { get; set; } = null!;

    public string PhoneExtension { get; set; } = null!;

    public string BillStreet { get; set; } = null!;

    public string BillApt { get; set; } = null!;

    public string? BillAptSuffix { get; set; }

    public string BillCity { get; set; } = null!;

    public string BillState { get; set; } = null!;

    public string BillZip { get; set; } = null!;

    public string BillCountry { get; set; } = null!;

    public int BillingId { get; set; }

    public string? Attention { get; set; }

    public string ShipApt { get; set; } = null!;

    public string? ShipAptSuffix { get; set; }

    public string ShipStreet { get; set; } = null!;

    public string ShipCity { get; set; } = null!;

    public string ShipState { get; set; } = null!;

    public string ShipZip { get; set; } = null!;

    public string ShipCountry { get; set; } = null!;

    public int ShippingId { get; set; }

    public string Active { get; set; } = null!;

    public string TaxExempt { get; set; } = null!;

    public string? FishbowlId { get; set; }

    public int? FailedAttempts { get; set; }

    public int? Unclaimed { get; set; }

    public int? AutoGenerated { get; set; }

    public DateTime? LastFailedAttemptAt { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string? DealerAppSubmitted { get; set; }

    public string? ConvertedFromUser { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new HashSet<Order>();
}
